config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  get 'kbio_mhci_result/show'
  get 'kbio_mhci_result/summary'
  get 'kbio_mhci_result/plot'
  get 'kbio_mhci_result/plot2'
  get 'kbio_mhci_result/report'

  get 'kbio_mhcii_result/show'
  get 'kbio_mhcii_result/summary'
  get 'kbio_mhcii_result/plot'
  get 'kbio_mhcii_result/plot2'
  get 'kbio_mhcii_result/report'

  get 'result/show'
  get 'result/summary'
  get 'result/plot'
  get 'result/plot2'
  get 'result/report'

  get 'mhci_result/show'
  get 'mhci_result/plot'

  get 'mhcii_result/show'
  get 'mhcii_result/plot'

  get 'jobs/show'

  resources :projects do
    resources :data
  end
  
  resources :analyses
  resources :analysis_steps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "projects#index"

end

app/models/analysis.rb
class Analysis < ApplicationRecord
  belongs_to :datum
  belongs_to :project
  has_one :tool_item
  has_one :itemable, through: :tool_item, source_type: "Itemable"
  has_one :result

  validates :title, presence: true
  validates :description, presence: true
  accepts_nested_attributes_for :tool_item, allow_destroy: true


  def check
    (title != nil and description != nil) ? true : false
  end
end

app/models/class_immu_item.rb
class ClassImmuItem < ApplicationRecord
  TYPE = "Class-I_Immunogenicity"
  belongs_to :datum
  has_one :tool_item, as: :itemable
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
end

app/models/datum.rb
class Datum < ApplicationRecord
    validates :name, presence: true
    validates :content, presence: true
    belongs_to :project
    has_many :analyses

    def FASTA?
        if content.start_with?(">")
            return true
        else
            return false
        end
    end
end

app/models/disco_tope_item.rb
class DiscoTopeItem < ApplicationRecord
    TYPE = "DiscoTope"
    has_one :tool_item, as: :itemable
end

app/models/ellipro_item.rb
class ElliproItem < ApplicationRecord
    TYPE = "ElliPro"
    has_one :tool_item, as: :itemable
end

app/models/kbio_mhci_item.rb
class KbioMhciItem < ApplicationRecord
  TYPE = "KBIO-MHC-I"
  belongs_to :datum
  has_one :tool_item, as: :itemable
  has_one :analysis, through: :tool_item

  def getType
    TYPE
  end

  def getArgs
    "#{percentile_rank}"
  end

  def getPercentileRank
    percentile_rank
  end

end

app/models/kbio_mhcii_item.rb
class KbioMhciiItem < ApplicationRecord
  TYPE = "KBIO-MHC-II"
  belongs_to :datum
  has_one :tool_item, as: :itemable
  has_one :analysis, through: :tool_item

  def getType
    TYPE
  end

  def getArgs
    "#{percentile_rank}"
  end

  def getPercentileRank
    percentile_rank
  end

end

app/models/mhci_item.rb
class MhciItem < ApplicationRecord
  TYPE = "MHC-I"
  belongs_to :datum
  has_one :tool_item, as: :itemable
  has_one :analysis, through: :tool_item
  #attr_accessor :prediction_method, :alleles, :output_sort

  def getType
    TYPE
  end

  def getArgs
    "#{prediction_method} \"#{alleles}\" #{length}"
  end

  def getMethod
    prediction_method
  end

  def getAlleles
    alleles
  end

  def getOutputSort
    output_sort
  end
end

app/models/mhci_result.rb
class MhciResult < ApplicationRecord
  belongs_to :result

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |result|
        csv << result.addributes.values_at(*column_names)
      end
    end
  end

end

app/models/mhcii_item.rb
class MhciiItem < ApplicationRecord
  TYPE = "MHC-II"
  belongs_to :datum
  has_one :tool_item, as: :itemable
  has_one :analysis, through: :tool_item

  def getType
    TYPE
  end

  def getArgs
    "#{prediction_method} \"#{alleles}\""
  end

  def getMethod
    prediction_method
  end

  def getAlleles
    alleles
  end

  def getOutputSort
    output_sort
  end

end

app/models/mhcii_result.rb
class MhciiResult < ApplicationRecord
  belongs_to :result

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |result|
        csv << result.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    validates :title, presence: true
    validates :title, length: {maximum: 100}
    has_many :data, dependent: :destroy
    has_many :analyses
    belongs_to :user
    
    def should_generate_new_friendly_id?
        title_changed?
    end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :analysis
end

app/models/tool_item.rb
class ToolItem < ApplicationRecord
  belongs_to :analysis
  belongs_to :itemable, polymorphic: true

  def getToolType
    self.itemable_type
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, authentication_keys: [:login]
  
  has_many :projects
  has_one :dashboard
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pbs_helper.rb
module PbsHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/layouts/shared/_footer.html.erb
<div class="pull-right">
  <%= image_tag("kbio_logo.jpg", :alt => "KBIO Health") %>
</div>
<div class="clearfix"></div>

app/views/layouts/shared/_leftnav.html.erb
<div class="navbar nav_title" style="border: 0;">
  <a href="/" class="site_title"><i class="fa fa-flask"></i> <span>Kepre</span></a>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<% if user_signed_in? %>
  <div class="profile clearfix">
    <div class="profile_pic">
    <%= image_tag("codegen.jpg", :alt => "...", :class =>"img-circle profile_img") %>
    </div>
    <div class="profile_info">
      <span>Welcome,</span>
      <h2><%= current_user.username %></h2>
    </div>
  </div>
<!-- /menu profile quick info -->
<% end %>
<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>General</h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-home"></i> Projects <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="/projects"><i class="fa fa-tachometer"></i>Project Dashboard</a></li>
          <% if user_signed_in? and @user_projects != nil  %>
            <% @user_projects.each do |project| %>
              <li><%= link_to "<i class='fa fa-cube'></i>#{project.title}".html_safe, project %></li>
            <% end %>
          <% end %>
        </ul>
      </li>
      <li><a><i class="fa fa-edit"></i>T Cell Epitope <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="/">MHC I Binding</a></li>
          <li><a href="/">MHC II Binding</a></li>
          <li><a href="/">MHC I processing</a></li>
          <li><a href="/">MHC I Immunogenicity</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-desktop"></i> B Cell Epitope <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="/">Antigen Sequence Properties</a></li>
          <li><a href="/">Discotope</a></li>
          <li><a href="/">ElliPro</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-tasks"></i> Job Monitoring <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><%= link_to "Analysis job list", jobs_show_path %></li>
        </ul>
      </li>
    </ul>
  </div>


</div>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  </a>
</div>
<!-- /menu footer buttons -->

app/views/layouts/shared/_topnav.html.erb
<div class="nav toggle">
  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
</div>

<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li class="">
      <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <%= image_tag("codegen.jpg", :alt => "...") %> <%= current_user.username %>
        <span class=" fa fa-angle-down"></span>
      </a>
      <ul class="dropdown-menu dropdown-usermenu pull-right">
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li>
          <a href="javascript:;">
            <span class="badge bg-red pull-right">50%</span>
            <span>Settings</span>
          </a>
        </li>
        <li><a href="javascript:;">Help</a></li>
        <li><%= link_to '<i class="fa fa-sign-out pull-right"></i> Log Out'.html_safe, destroy_user_session_path, method: :delete %></li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
    <li><%= link_to "Login", new_user_session_path %></li>
  <% end %>
</ul>