config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  get 'kbio_mhci_result/show'
  get 'kbio_mhci_result/summary'
  get 'kbio_mhci_result/plot'
  get 'kbio_mhci_result/plot2'
  get 'kbio_mhci_result/report'

  get 'kbio_mhcii_result/show'
  get 'kbio_mhcii_result/summary'
  get 'kbio_mhcii_result/plot'
  get 'kbio_mhcii_result/plot2'
  get 'kbio_mhcii_result/report'

  get 'result/show'
  get 'result/summary'
  get 'result/plot'
  get 'result/plot2'
  get 'result/report'

  get 'mhci_result/show'
  get 'mhci_result/plot'

  get 'mhcii_result/show'
  get 'mhcii_result/plot'

  get 'jobs/show'

  resources :projects do
    resources :data
  end
  
  resources :analyses
  resources :analysis_steps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "projects#index"

end

app/models/analysis.rb
class Analysis < ApplicationRecord
  belongs_to :datum
  belongs_to :project
  has_one :tool_item
  has_one :itemable, through: :tool_item, source_type: "Itemable"
  has_one :result

  validates :title, presence: true
  validates :description, presence: true
  accepts_nested_attributes_for :tool_item, allow_destroy: true


  def check
    (title != nil and description != nil) ? true : false
  end
end

app/models/class_immu_item.rb
class ClassImmuItem < ApplicationRecord
  TYPE = "Class-I_Immunogenicity"
  belongs_to :datum
  has_one :tool_item, as: :itemable
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
end

app/models/datum.rb
class Datum < ApplicationRecord
    validates :name, presence: true
    validates :content, presence: true
    belongs_to :project
    has_many :analyses

    def FASTA?
        if content.start_with?(">")
            return true
        else
            return false
        end
    end
end

app/models/disco_tope_item.rb
class DiscoTopeItem < ApplicationRecord
    TYPE = "DiscoTope"
    has_one :tool_item, as: :itemable
end

app/models/ellipro_item.rb
class ElliproItem < ApplicationRecord
    TYPE = "ElliPro"
    has_one :tool_item, as: :itemable
end

app/models/kbio_mhci_item.rb
class KbioMhciItem < ApplicationRecord
  TYPE = "KBIO-MHC-I"
  belongs_to :datum
  has_one :tool_item, as: :itemable
  has_one :analysis, through: :tool_item

  def getType
    TYPE
  end

  def getArgs
    "#{percentile_rank}"
  end

  def getPercentileRank
    percentile_rank
  end

end

app/models/kbio_mhcii_item.rb
class KbioMhciiItem < ApplicationRecord
  TYPE = "KBIO-MHC-II"
  belongs_to :datum
  has_one :tool_item, as: :itemable
  has_one :analysis, through: :tool_item

  def getType
    TYPE
  end

  def getArgs
    "#{percentile_rank}"
  end

  def getPercentileRank
    percentile_rank
  end

end

app/models/kbio_mhcii_result.rb
class KbioMhciiResult < ApplicationRecord
  belongs_to :result
end

app/models/mhci_item.rb
class MhciItem < ApplicationRecord
  TYPE = "MHC-I"
  belongs_to :datum
  has_one :tool_item, as: :itemable
  has_one :analysis, through: :tool_item
  #attr_accessor :prediction_method, :alleles, :output_sort

  def getType
    TYPE
  end

  def getArgs
    "#{prediction_method} \"#{alleles}\" #{length}"
  end

  def getMethod
    prediction_method
  end

  def getAlleles
    alleles
  end

  def getOutputSort
    output_sort
  end
end

app/models/mhci_result.rb
class MhciResult < ApplicationRecord
  belongs_to :result

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |result|
        csv << result.addributes.values_at(*column_names)
      end
    end
  end

end

app/models/mhcii_item.rb
class MhciiItem < ApplicationRecord
  TYPE = "MHC-II"
  belongs_to :datum
  has_one :tool_item, as: :itemable
  has_one :analysis, through: :tool_item

  def getType
    TYPE
  end

  def getArgs
    "#{prediction_method} \"#{alleles}\""
  end

  def getMethod
    prediction_method
  end

  def getAlleles
    alleles
  end

  def getOutputSort
    output_sort
  end

end

app/models/mhcii_result.rb
class MhciiResult < ApplicationRecord
  belongs_to :result

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |result|
        csv << result.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    validates :title, presence: true
    validates :title, length: {maximum: 100}
    has_many :data, dependent: :destroy
    has_many :analyses
    belongs_to :user
    
    def should_generate_new_friendly_id?
        title_changed?
    end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :analysis
end

app/models/tool_item.rb
class ToolItem < ApplicationRecord
  belongs_to :analysis
  belongs_to :itemable, polymorphic: true

  def getToolType
    self.itemable_type
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, authentication_keys: [:login]
  
  has_many :projects
  has_one :dashboard
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/kbio_mhcii_result_controller.rb
class KbioMhciiResultController < ApplicationController
  def show
    @results = MhciiResult.where("result_id = ?", params[:result_id])
    @analysis = Analysis.find(params[:analysis_id])
    @project = @analysis.project
    @datum = @analysis.datum
    respond_to do |format|
      format.html
      format.csv { send_data @results.to_csv}
      format.xls #{ send_data @results.to_csv(col_sep: "\t")}
    end

  end

  def summary
    @results = KbioMhciiResult.where("result_id = ?", params[:result_id])
    @analysis = Analysis.find(params[:analysis_id])
    @project = @analysis.project
    @datum = @analysis.datum
  end

  def plot
    @results = Result.find_by_id(params[:result_id])
    @json = read_file(@results.output)
    @analysis = Analysis.find(params[:analysis_id])
    @project = @analysis.project
    @datum = @analysis.datum
  end

  def plot2
    @results = Result.find_by_id(params[:result_id])
    @json = read_file(@results.output2)
    @analysis = Analysis.find(params[:analysis_id])
    @project = @analysis.project
    @datum = @analysis.datum
  end


  def report
    @rawdata = KbioMhciiResult.where("result_id = ? and score < 1", params[:result_id]).order(score: :asc, allele: :desc)
    #@rawdata = MhciResult.where("result_id = ? and percentile_rank < 0.5", params[:result_id]).order(percentile_rank: :asc).distinct
    @results = Result.find_by_id(params[:result_id])
    #@json = read_file(@results.output)
    @analysis = Analysis.find(params[:analysis_id])
    @seq = @analysis.datum

    pdf = ReportPdf.new(@analysis, @rawdata, @seq, "MHC II")
    send_data pdf.render, filename: "analysis_report.pdf", type: "application/pdf" , disposition: "inline"
  end

  def read_file(file_name)
    file = File.open(file_name, "r")
    data = file.read
    file.close
    return data
  end

end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pbs_helper.rb
module PbsHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/kbio_mhcii_result/plot.html.erb
<% provide(:title, "Result | #{@analysis.title}") %>
<%= stylesheet_link_tag  "kbio_mhcii_result", :media => "all" %>

<div class="page-title">
    <div class="title_left">
        <h3><%= @analysis.title %> <b> score : <%= @results.score %><b></h3>
    </div>

    <div class="title_right">
        <div class="col-xs-12">              
            <%= link_to 'Back', project_datum_path(@project, @datum), :class=>"btn btn-success pull-right" %>
        </div>
    </div>
</div>

<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            
            <%= content_tag :div, "", id: "KBIO_MHCII_chart", style: "height: 1200px;", data: {results: @json} %>

        </div>
    </div>
</div>

app/views/kbio_mhcii_result/plot2.html.erb
<% provide(:title, "Result | #{@analysis.title}") %>
<%= stylesheet_link_tag    "kbio_mhcii_result", :media => "all" %>

<div class="page-title">
    <div class="title_left">
        <h3><%= @analysis.title %> <b> score : <%= @results.score %><b></h3>
    </div>

    <div class="title_right">

        <div class="col-xs-12">              
            <%= link_to 'Back', project_datum_path(@project, @datum), :class=>"btn btn-success pull-right" %>
        </div>

    </div>
</div>

<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            
            <%= content_tag :div, "", id: "KBIO_MHCII_chart", style: "height: 1200px;", data: {results: @json} %>

        </div>
    </div>
</div>

app/views/kbio_mhcii_result/show.html.erb
<% provide(:title, "Result | #{@analysis.title}") %>


<div class="page-title">
    <div class="title_left">
    <h3><%= @analysis.title %></h3>
    </div>

    <div class="title_right">
        <div class="title_right">

            <div class="col-xs-12">              
                <%= link_to 'Back', project_datum_path(@project, @datum), :class=>"btn btn-success pull-right" %>
            </div>
    
        </div>
    </div>
</div>

<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
        <h2>Analysis Result for MHC II <small><%= @analysis.title %></small></h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-download"></i></a>
            <ul class="dropdown-menu" role="menu">
                <li><%= link_to "CSV", kbio_mhcii_result_show_path( :result_id => params[:result_id], :analysis_id => params[:analysis_id], :format => "csv") %>
                </li>
                <li><%= link_to "Excel", kbio_mhcii_result_show_path( :result_id => params[:result_id], :analysis_id => params[:analysis_id], :format => "xls") %>
                </li>
            </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
        </div>
        <div class="x_content">
        <p class="text-muted font-13 m-b-30">
        <%= @analysis.description %>
        </p>
        <p>
            <%= link_to "CSV", kbio_mhcii_result_show_path( :result_id => params[:result_id], :analysis_id => params[:analysis_id], :format => "csv"), :class=>"btn btn-primary" %>
            <%= link_to "Excel", kbio_mhcii_result_show_path( :result_id => params[:result_id], :analysis_id => params[:analysis_id], :format => "xls"), :class=>"btn btn-primary" %>
        </p>

        <table id="datatable" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>allele</th>
                <th>seq_num</th>
                <th>start</th>
                <th>end</th>
                <th>peptide</th>
                <th>method</th>
                <th>consensus_percentile_rank</th>
                <th>comblib_core</th>
                <th>comblib_score</th>
                <th>comblib_rank</th>
                <th>smm_align_core</th>
                <th>smm_align_ic50</th>
                <th>smm_align_rank</th>
                <th>nn_align_core</th>
                <th>nn_align_ic50</th>
                <th>nn_align_rank</th>
                <th>netmhciipan_core</th>
                <th>netmhciipan_ic50</th>
                <th>netmhciipan_rank</th>
                <th>sturniolo_core</th>
                <th>sturniolo_score</th>
                <th>sturniolo_rank</th>
            </tr>
            </thead>

            <tbody>

            <% @results.each do |result| %>
                <tr>
                    <td><%= result.allele %></td>
                    <td><%= result.seq_num %></td>
                    <td><%= result.start %></td>
                    <td><%= result.end %></td>
                    <td><%= result.peptide %></td>
                    <td><%= result.method %></td>
                    <td><%= result.consensus_percentile_rank %></td>
                    <td><%= result.comblib_core %></td>
                    <td><%= result.comblib_score %></td>
                    <td><%= result.comblib_rank %></td>
                    <td><%= result.smm_align_core %></td>
                    <td><%= result.smm_align_ic50 %></td>
                    <td><%= result.smm_align_rank %></td>
                    <td><%= result.nn_align_core %></td>
                    <td><%= result.nn_align_ic50 %></td>
                    <td><%= result.nn_align_rank %></td>
                    <td><%= result.netmhciipan_core %></td>
                    <td><%= result.netmhciipan_ic50 %></td>
                    <td><%= result.netmhciipan_rank %></td>                    
                    <td><%= result.sturniolo_core %></td>
                    <td><%= result.sturniolo_score %></td>
                    <td><%= result.sturniolo_rank %></td>                                  
                </tr>
            <% end %>

            </tbody>
        </table>
    </div>
</div>

app/views/kbio_mhcii_result/show.xls.erb
<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" 
xmlns:x="urn:schemas-microsoft-com:office:excel" 
xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" 
xmlns:html="http://www.w3.org/TR/REC-html40">
<Worksheet ss:Name="Sheet1">
<Table>
<Column ss:Index="1" ss:AutoFitWidth="0" ss:Width="110"/>
<Row>
    <Cell><Data ss:Type="String">allele</Data></Cell>
    <Cell><Data ss:Type="String">seq_num</Data></Cell>
    <Cell><Data ss:Type="String">start</Data></Cell>
    <Cell><Data ss:Type="String">end</Data></Cell>
    <Cell><Data ss:Type="String">peptide</Data></Cell>
    <Cell><Data ss:Type="String">method</Data></Cell>
    <Cell><Data ss:Type="String">consensus_percentile_rank</Data></Cell>
    <Cell><Data ss:Type="String">comblib_core</Data></Cell>
    <Cell><Data ss:Type="String">comblib_score</Data></Cell>
    <Cell><Data ss:Type="String">comblib_rank</Data></Cell>
    <Cell><Data ss:Type="String">smm_align_core</Data></Cell>
    <Cell><Data ss:Type="String">smm_align_ic50</Data></Cell>
    <Cell><Data ss:Type="String">smm_align_rank</Data></Cell>
    <Cell><Data ss:Type="String">nn_align_core</Data></Cell>
    <Cell><Data ss:Type="String">nn_align_ic50</Data></Cell>
    <Cell><Data ss:Type="String">nn_align_rank</Data></Cell>
    <Cell><Data ss:Type="String">netmhciipan_core</Data></Cell>
    <Cell><Data ss:Type="String">netmhciipan_ic50</Data></Cell>
    <Cell><Data ss:Type="String">netmhciipan_rank</Data></Cell>
    <Cell><Data ss:Type="String">sturniolo_core</Data></Cell>
    <Cell><Data ss:Type="String">sturniolo_score</Data></Cell>
    <Cell><Data ss:Type="String">sturniolo_rank</Data></Cell>
</Row>
<% @results.each do |result| %>
<Row>
    <Cell><Data ss:Type="String"><%= result.allele %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.seq_num %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.start %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.end %></Data></Cell>
    <Cell><Data ss:Type="String"><%= result.peptide %></Data></Cell>
    <Cell><Data ss:Type="String"><%= result.method %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.consensus_percentile_rank %></Data></Cell>
    <Cell><Data ss:Type="String"><%= result.comblib_core %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.comblib_score %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.comblib_rank %></Data></Cell>
    <Cell><Data ss:Type="String"><%= result.smm_align_core %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.smm_align_ic50 %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.smm_align_rank %></Data></Cell>
    <Cell><Data ss:Type="String"><%= result.nn_align_core %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.nn_align_ic50 %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.nn_align_rank %></Data></Cell>
    <Cell><Data ss:Type="String"><%= result.netmhciipan_core %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.netmhciipan_ic50 %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.netmhciipan_rank %></Data></Cell>                   
    <Cell><Data ss:Type="String"><%= result.sturniolo_core %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.sturniolo_score %></Data></Cell>
    <Cell><Data ss:Type="Number"><%= result.sturniolo_rank %></Data></Cell>                   
</Row>
<% end %>
</Table>
</Worksheet>
</Workbook>

app/views/kbio_mhcii_result/summary.html.erb
<% provide(:title, "Result | #{@analysis.title}") %>


<div class="page-title">
    <div class="title_left">
    <h3><%= @analysis.title %></h3>
    </div>

    <div class="title_right">
        <div class="title_right">

            <div class="col-xs-12">              
                <%= link_to 'Back', project_datum_path(@project, @datum), :class=>"btn btn-success pull-right" %>
            </div>
    
        </div>
    </div>
</div>

<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Analysis Result for MHC II <small><%= @analysis.title %></small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                    </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                <%= @analysis.description %>
                </p>
                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>seq id</th>
                        <th>aa</th>
                        <th>allele</th>
                        <th>score</th>
                    </tr>
                    </thead>

                    <tbody>

                    <% @results.each do |result| %>
                        <tr>
                            <td><%= result.seq_id %></td>
                            <td><%= result.aa %></td>
                            <td><%= result.allele %></td>
                            <td><%= result.score %></td>                                 
                        </tr>
                    <% end %>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>