config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  get 'kbio_mhci_result/show'
  get 'kbio_mhci_result/summary'
  get 'kbio_mhci_result/plot'
  get 'kbio_mhci_result/plot2'
  get 'kbio_mhci_result/report'

  get 'kbio_mhcii_result/show'
  get 'kbio_mhcii_result/summary'
  get 'kbio_mhcii_result/plot'
  get 'kbio_mhcii_result/plot2'
  get 'kbio_mhcii_result/report'

  get 'result/show'
  get 'result/summary'
  get 'result/plot'
  get 'result/plot2'
  get 'result/report'

  get 'mhci_result/show'
  get 'mhci_result/plot'

  get 'mhcii_result/show'
  get 'mhcii_result/plot'

  get 'jobs/show'

  resources :projects do
    resources :data
  end
  
  resources :analyses
  resources :analysis_steps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "projects#index"

end

app/controllers/data_controller.rb
require 'bio'
require 'stringio'

class DataController < ApplicationController
  before_action :get_project
  before_action :set_datum, only: [:show, :edit, :update, :destroy]

  def get_project
    @project = Project.friendly.find(params[:project_id])
  end

  # GET /data
  # GET /data.json
  def index
    @datum = @project.data.all
  end

  # GET /data/1
  # GET /data/1.json
  def show
    @analyses = Analysis.where( datum_id: @datum.id)
    @fasta = Bio::FastaFormat.new(@datum.content)
    @donut_data = @fasta.aaseq.composition.map { |seq, comp| {"label" => seq, "value" => comp}}

  end

  # GET /data/new
  def new
    @datum = @project.data.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  # POST /data.json
  def create

    flag = 0
    count = 0
    if params[:datum][:content] != nil and params[:datum][:data_type] =="FASTA"

      fasta_cont = StringIO.new(params[:datum][:content])
      seqs = Bio::FlatFile.auto(fasta_cont)
      check = seqs.count
      if check == 1
        puts "enter 1"
        @datum = @project.data.new(datum_params)
        if @datum.save
          flag = 1
          count = 1
        end

      elsif check > 1
        puts "enter 2"
        fasta_cont = StringIO.new(params[:datum][:content])
        seqs = Bio::FlatFile.auto(fasta_cont)
        seqs.each do |seq|
          puts seq
          count = count + 1
          title = "#{params[:datum][:name]}_#{count}"
          type = params[:datum][:data_type]

          @datum = @project.data.new()
          @datum.name = title
          @datum.content = seq
          @datum.data_type = type
          if @datum.save
            flag = 1
          end
        end
      end

    elsif params[:datum][:data_type] =="PDB"

      @datum = @project.data.new(datum_params)
      if @datum.save
        flag = 1
        count = 1
      end

    end



    respond_to do |format|
      if flag #@datum.save
        update_data_info(count)
        format.html { redirect_to project_url(@project), notice: 'Datum was successfully created.' }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1
  # PATCH/PUT /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to project_url(@project), notice: 'Datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url, notice: 'Datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params.require(:datum).permit(:name, :content, :data_type)
    end

    # Get the project object
    #def get_project
    #  @project = Project.find(params[:project_id])
    #end

    def update_data_info(count)
      @dashboard = current_user.dashboard
      @curr_data = @dashboard.total_data
      @dashboard.total_data = @curr_data + count
      @dashboard.save
    end
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
        <div class="clearfix"></div>
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <!-- %= @title % -->
                <%= @title %>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <br />
                  <%= form_with(model: [@project, @datum], class: "form-horizontal form-label-left", id: "demo-form2") do |form| %>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Name <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= form.text_field :name, id: :datum_name, class: 'form-control col-md-7 col-xs-12', required: true %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Content <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= form.text_area :content, id: :datum_content , cols: 80, rows: 20, class: 'resizable_textarea form-control', placeholder: 'Add your data' %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Data type <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= form.select :data_type, ['FASTA', 'PDB'], :prompt => 'Select data type', class: 'form-control col-md-7 col-xs-12', required: true %>
                      
                    </div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                      <button class="btn btn-primary" type="button">Cancel</button>
				              <button class="btn btn-primary" type="reset">Reset</button>
                      <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                  </div>

                <% end %>
              </div>
            </div>
          </div>
        </div>

app/views/data/edit.html.erb
<% provide(:title, 'Edit Data') %>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Edit Data</h3>
        </div>
    </div>


<%= render 'form', project: @project, datum: @datum %>

<%= link_to 'Back', project_path(@project) %>

</div>

app/views/data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.name %></td>
        <td><%= datum.content %></td>
        <td><%= datum.data_type %></td>
        <td><%= link_to 'Show', datum %></td>
        <td><%= link_to 'Edit', edit_datum_path(datum) %></td>
        <td><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datum', new_project_datum_path %>

app/views/data/new.html.erb
<% provide(:title, 'New Data') %>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>New Data</h3>
        </div>
    </div>


<%= render 'form', project: @project, datum: @datum %>

<%= link_to 'Back', project_path(@project) %>

</div>

app/views/data/show.html.erb
        <!-- page content -->
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Data Detail <small>   <strong>Type:</strong> <%= @datum.data_type %> </small></h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><strong>Name:</strong> <%= @datum.name %></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <div>
                      <!-- data content -->
                            <pre><%= @datum.content %></pre>
                      </div>

                      <div>

                        <h4>Analysis List</h4>

                        <!-- /.row -->
                        <div class="clearfix"></div>
                        <!-- Table row -->
                        <div class="row">
                          <div class="col-xs-12 table">
                            <table class="table table-striped">
                              <thead>
                                <tr>
                                  <th>#</th>
                                  <th>Name</th>
                                  <th>Description</th>
                                  <th>Tool</th>
                                  <th>Status</th>
                                </tr>
                              </thead>
                              <tbody>
                              <% if @analyses != nil %>
                                <% @analyses.each do |analysis| %>
                                <tr>
                                  <% @tool_content = analysis.tool_item.itemable.getType %>
                                  <td><%= analysis.id %></td>
                                  <td><%= analysis.title %></td>
                                  <td><%= analysis.description %></td>
                                  <td><%= @tool_content %></td>
                                  <td> 
                                  <button type="button" class="btn btn-info btn-sm"> <span class="glyphicon glyphicon-cog"></span> <%= analysis.status %> </button> 
                                  <% result = analysis.result %>
                                  <% if analysis.status == "Finish" %>
                                  <%= link_to '<i class="fa fa-wrench"></i> Result Table'.html_safe, result_show_path(:tool_type => @tool_content, :result_id => result.id, :analysis_id => analysis.id ), :class=>"btn btn-primary" %>
                                  <%= link_to '<i class="fa fa-wrench"></i> Plot'.html_safe, result_plot_path(:tool_type => @tool_content, :result_id => result.id, :analysis_id => analysis.id ), :class=>"btn btn-primary" %>
                                    <% if @tool_content == "KBIO-MHC-I" or @tool_content == "KBIO-MHC-II" %>
                                    <%= link_to '<i class="fa fa-wrench"></i> Result(summary)'.html_safe, result_summary_path(:tool_type => @tool_content, :result_id => result.id, :analysis_id => analysis.id ), :class=>"btn btn-primary" %>
                                    <%= link_to '<i class="fa fa-wrench"></i> Plot(summary)'.html_safe, result_plot2_path(:tool_type => @tool_content, :result_id => result.id, :analysis_id => analysis.id ), :class=>"btn btn-primary" %>
                                    <%= link_to '<i class="fa fa-wrench"></i> Report'.html_safe, result_report_path(:tool_type => @tool_content, :result_id => result.id, :analysis_id => analysis.id ), :class=>"btn btn-primary", :target => "_blank" %>
                                    <% end %>
                                  <% end %>
                                  <!-- %= link_to 'Show', project_datum_path(@project, datum.id) % -->
                                  <!-- %= link_to 'Edit', edit_project_datum_path(@project, datum) % --></td>
                                </tr>
                                <%end%>
                              <% else %>
                                <tr><td colspan="4">Try our fisrt analysis with this data </td></tr>
                              <% end %>
                              </tbody>
                            </table>
                          </div>
                          <!-- /.col -->
                        </div>
                        <!-- /.row -->
                        <!-- this row will not appear when printing -->
                        <div class="row no-print">
                          <div class="col-xs-12">              

                            <%= link_to 'Back', project_path(@project), :class=>"btn btn-success pull-right" %>
                            <%= link_to 'Edit', edit_project_datum_path(@datum), :class=>"btn btn-success pull-right" %> 
                            <%= link_to '<i class="fa fa-wrench"></i> New Analysis'.html_safe, new_analysis_path(project_id: @project, datum_id: @datum), :class=>"btn btn-primary pull-right", :style=>"margin-right: 5px;" %>
                            
                          </div>
                        </div>

                      </div>


                    </div>

                    <!-- start project-detail sidebar -->
                    <div class="col-md-3 col-sm-3 col-xs-12">

                      <section class="panel">

                        <div class="x_title">
                          <h2>Data statistics</h2>
                          <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                          <h3 class="green"><i class="fa fa-bolt"></i> <%= @datum.name %></h3>

                          <p><%= @datum.name %></p>
                          <br />

                          <div class="project_detail">

                            <p class="title">Data type</p>
                            <p><%= @datum.data_type%></p>
                            <p class="title">Created date</p>
                            <p><%= @datum.created_at.strftime("%F %H:%M")%></p>
                            <p class="title">Updated date</p>
                            <p><%= @datum.updated_at.strftime("%F %H:%M")%></p>
                          </div>
                          <% if @datum.data_type =="FASTA" %>
                          <br />
                          <h5>Sequence info</h5>
                          <ul class="list-unstyled project_files">
                            <li><i class="fa fa-file-word-o"></i> Length : <%= @fasta.length %>
                            </li>
                            <li><i class="fa fa-file-word-o"></i> MW : <%= @fasta.aaseq.molecular_weight %>
                            </li>
                            <li><i class="fa fa-file-pdf-o"></i> Composition : 
                            </li>
                            <%= content_tag :div, "", id: "seq_chart", style: "height: 200px;", data: {results: @donut_data} %>
                          </ul>
                          <br />
                          <% end %> 
                        </div>
                      </section>
                    </div>
                    <!-- end project-detail sidebar -->

                  </div>
                </div>
              </div>
            </div>
          </div>

        <!-- /page content -->